### ISSUE TITLE
Search Reading Locations

### ISSUE THREAD

**Issue by AninhasGMIT** [liam2255/Star-Media#3]

**Comment by liam2255** [comment]
https://github.com/liam2255/Star-Media/blob/86b5f359cc2e7c701a37eb038e1fdfb9cddc7e60/search.html#L614-L828

**Comment by liam2255** [comment]
https://github.com/liam2255/Star-Media/blob/86b5f359cc2e7c701a37eb038e1fdfb9cddc7e60/css/customCho.css#L228-L278
