### ISSUE TITLE
"View all" 

### ISSUE THREAD

**Issue by AninhasGMIT** [liam2255/Star-Media#7]

**Comment by liam2255** [comment]
https://github.com/liam2255/Star-Media/blob/86b5f359cc2e7c701a37eb038e1fdfb9cddc7e60/viewAll.html#L1-L1160

**Comment by liam2255** [comment]
https://github.com/liam2255/Star-Media/blob/86b5f359cc2e7c701a37eb038e1fdfb9cddc7e60/css/customCho.css#L189-L224
